protected/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;

/**
 * Class SiteController
 * @package app\controllers
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['help', 'api-log', 'api-response-log'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['admin', 'manager'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Homepage.
     */
    public function actionIndex()
    {
        if (Yii::$app->user->isGuest)
            $this->redirect(['site/login']);
        else
            $this->redirect(['payment/index']);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
//    public function actionContact()
//    {
//        $model = new ContactForm();
//        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
//            Yii::$app->session->setFlash('contactFormSubmitted');
//
//            return $this->refresh();
//        }
//        return $this->render('contact', [
//            'model' => $model,
//        ]);
//    }

    /**
     * @return string
     */
    public function actionHelp()
    {
        return $this->render('help');
    }

    /**
     * @return string
     */
    public function actionApiLog()
    {
        $response = Yii::$app->getResponse();
        $response->format = Response::FORMAT_RAW;
        $response->headers->set('Content-Type', 'text/plain; charset=UTF-8');

        return @file_get_contents(
            Yii::getAlias('@runtime/logs/api.log')
        );
    }

    /**
     * @return string
     */
    public function actionApiResponseLog()
    {
        $response = Yii::$app->getResponse();
        $response->format = Response::FORMAT_RAW;
        $response->headers->set('Content-Type', 'text/plain; charset=UTF-8');

        return @file_get_contents(
            Yii::getAlias('@runtime/logs/api_response.log')
        );
    }

    /**
     * @return string
     */
    public function actionRedoc()
    {
        $this->layout = 'api_layout';
        return $this->render('redoc');
    }

}

protected/controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use yii\db\IntegrityException;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Transaction;
use app\models\UserSearch;
use app\models\User;
use app\models\Report;
use app\models\Payment;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'roles' => ['admin'],
                        'allow' => true,
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $auth = Yii::$app->authManager;
            $type = $model->type;
            switch ($type) {
                case User::TYPE_USER :
                    $user = $auth->getRole('user');
                    $auth->assign($user, $model->getId());
                    break;
                case User::TYPE_MANAGER :
                    $manager = $auth->getRole('manager');
                    $auth->assign($manager, $model->getId());
                    break;
                case User::TYPE_ADMIN :
                    $admin = $auth->getRole('admin');
                    $auth->assign($admin, $model->getId());
                    break;
            }
            
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }
        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        try {
	    Report::deleteAll('user_id = :user_id', [':user_id' => $id]);
	    Payment::deleteAll('user_id = :user_id', [':user_id' => $id]);
	    Transaction::deleteAll('user_id = :user_id', [':user_id' => $id]);
            $this->findModel($id)->delete();
        } catch (IntegrityException $e) {
            Yii::$app->session->addFlash('error', 'Ошибка: '.$e);
        }

        return $this->redirect(['index']);
    }

    public function actionRecalculateBalances()
    {
        $affected = User::recalculateBalances();
        return $this->render('@app/views/site/message', [
            'message'=>"Балансы пользователей пересчитаны.\nЗатронуто пользователей: $affected."
        ]);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        /* @var User $model */
        $model = User::find()
            ->select('u.*,
                count(r.id) AS count_referrers,
                sum(t.amount) * count(distinct t.id) / count(t.id) AS sum_rewards_for_referrers')
            ->alias('u')
            ->leftJoin(User::tableName().' r', 'u.id = r.referrer_user_id')
            ->leftJoin(Transaction::tableName().' t', 'u.id = t.user_id AND t.type = :type')
            ->addParams([':type'=>Transaction::TYPE_REFERRAL_REWARD])
            ->groupBy('u.id')
            ->where(['u.id' => $id])
            ->one();

        if ($model !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

protected/views/layouts/api_layout.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<?= $content ?>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

protected/views/layouts/main.php
<?php

use app\widgets\Alert;
use yii\helpers\Html;
use yii\widgets\Breadcrumbs;

$bundle = yiister\gentelella\assets\Asset::register($this);
?>
<?php $this->beginPage(); ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta charset="<?= Yii::$app->charset ?>"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <?= Html::csrfMetaTags() ?>
  <title><?= Html::encode($this->title) ?></title>
  <?php $this->head() ?>
</head>
<body class="nav-<?= !empty($_COOKIE['menuIsCollapsed']) && $_COOKIE['menuIsCollapsed'] == 'true' ? 'sm' : 'md' ?>">
<?php $this->beginBody(); ?>
<div class="container body">
  <div class="main_container">
    <?php if (!Yii::$app->user->isGuest): ?>
      <div class="col-md-3 left_col">
        <div class="left_col scroll-view">
          <div class="navbar nav_title" style="border: 0;">
            <a href="/" class="site_title">
              <i class="fa fa-paw"></i>
              <span>Reward</span>
            </a>
          </div>
          <div class="clearfix"></div>
          <div class="profile">
            <div class="profile_pic">
              <img src="http://placehold.it/128x128" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
              <span>Добро пожаловать,</span>
              <h2>
                <?= Yii::$app->user->identity->login ?>
              </h2>
            </div>
          </div>
          <br>
          <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
              <h3>Меню</h3>
              <?=
              \yiister\gentelella\widgets\Menu::widget(
                [
                  "items" => [
                    ['label' => 'Выплаты', 'url' => ['/payment/index'], "icon" => "files-o"],
                    ['label' => 'Отчеты', 'url' => ['/report/index']],
                    ['label' => 'Транзакции', 'url' => ['/transaction/index']],
                    ['label' => 'Пользователи', 'url' => ['/user/index']],
                    ['label' => 'Дополнительные поля', 'url' => ['/extra-field/index']],
                    ['label' => 'Еще',
                      'url' => '#',
                      'items' =>
                      [
                        ['label' => 'Приложения', 'url' => ['/application/index']],
                        ['label' => 'Типы заданий', 'url' => ['/task-type/index']],
                        ['label' => 'Помощь', 'url' => ['/site/help']],
                      ]
                    ],
                  ],
                ]
              )
              ?>
            </div>
          </div>
        </div>
      </div>
      <div class="top_nav">
        <div class="nav_menu">
          <nav class="" role="navigation">
            <div class="nav toggle">
              <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>
            <ul class="nav navbar-nav navbar-right">
              <li class="">
                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                  <img src="http://placehold.it/128x128" alt="">
                  <?= Yii::$app->user->identity->login ?>
                  <span class=" fa fa-angle-down"></span>
                </a>
                <ul class="dropdown-menu dropdown-usermenu pull-right">
                  <li>
                    <a href="#">
                      <i class="fa fa-sign-out pull-right"></i>
                      <?= Html::beginForm(['/site/logout'], 'post') ?>
                      <?= Html::submitButton('Выйти',
                        [
                          'class' => 'btn btn-link'
                        ]) ?>
                      <?= Html::endForm() ?>
                    </a>
                  </li>
                </ul>
              </li>
            </ul>
          </nav>
        </div>
      </div>
      <?php else: ?>
      <div class="col-md-3 left_col">
        <div class="left_col scroll-view">
          <div class="navbar nav_title" style="border: 0;">
            <a href="/" class="site_title">
              <i class="fa fa-paw"></i>
              <span>Reward</span>
            </a>
          </div>
          <div class="clearfix"></div>
          <div class="profile">
            <div class="profile_info">
            </div>
          </div>
          <br/>
          <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
            </div>
          </div>
        </div>
      </div>
    <?php endif; ?>
    <div class="right_col" role="main">
      <?php if (isset($this->params['h1'])): ?>
        <div class="page-title">
          <div class="title_left">
            <h1><?= $this->params['h1'] ?></h1>
          </div>
          <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                  <button class="btn btn-default" type="button">Go!</button>
                </span>
              </div>
            </div>
          </div>
        </div>
      <?php endif; ?>
      <div class="clearfix"></div>
      <?= Breadcrumbs::widget([
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
      ]) ?>
      <?= Alert::widget() ?>
      <div class="container">
        <?= $content ?>
      </div>
    </div>
    <footer>
      <div class="pull-right">
        Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com" rel="nofollow"
                                                    target="_blank">Colorlib</a><br/>
        Extension for Yii framework 2 by <a href="http://yiister.ru" rel="nofollow" target="_blank">Yiister</a>
      </div>
      <div class="clearfix"></div>
    </footer>
  </div>
</div>
<div id="custom_notifications" class="custom-notifications dsp_none">
  <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group">
  </ul>
  <div class="clearfix"></div>
  <div id="notif-group" class="tabbed_notifications"></div>
</div>
<?php $this->endBody(); ?>
</body>
</html>
<?php $this->endPage(); ?>